version: '3.7'

x-build-args: &build_args
  APP_NAME: validation-service-tools
  APP_DESCRIPTION: "Validation Service Tools"
  APP_MAINTAINER: rcarr@chewy.com
  APP_VERSION: 1.0.0

services:

  umberdev: &devbox
    image: "umberdev"
    build:
      dockerfile: Dockerfile
      context: .
      args:
        <<: *build_args
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    volumes:
      - ./src/:/app/
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: umber.env
